scene:
  scene_path: /ocean/projects/cis250226p/shared/semantic-gaussian/dataset/data/scene0020_00
  dataset_name: scannet
  test_cameras: false
  colmap_images: color
  colmap_eval_hold: 8
  downscale_ratio: 1
  white_background: false
  device: cuda:0
pipeline:
  convert_shs_python: false
  compute_cov3d_python: false
  debug: false
  seed: 0
model:
  sh_degree: 3
  model_dir: /ocean/projects/cis250226p/shared/semantic-gaussian/output/scene0020_00
  dynamic: false
  load_iteration: -1
  device: cuda:0
fusion:
  img_dim:
  - 648
  - 484
  num_workers: 8
  model_2d: openseg
  depth: render
  depth_scale: 1000.0
  visibility_threshold: 0.05
  cut_boundary: 10
  n_split_points: 999999999
  num_rand_file_per_scene: 1
  out_dir: /ocean/projects/cis250226p/shared/semantic-gaussian/fusion_output/scene0020_00
